### ISSUE TITLE
Chore: Please make me Fly.io App Admin 🙏 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/calendar#28]
@LuchoTurtle I just tried to add payment method to the Fly,io `dwyl-calendar` App.
https://fly.io/dashboard/dwyl-calendar
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/194400/236027086-e4c174a1-6e42-4e90-b81e-0a731e13fc1b.png">

Please: 
+ [ ] promote the `user` https://fly.io/dashboard/dwyl-calendar/team to `admin` 👍 

Thanks.

**Comment by LuchoTurtle** [comment]
Done 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/17494745/236055096-587455b4-f97a-437c-b265-6616d119215a.png">

**Comment by nelsonic** [comment]
Thanks @LuchoTurtle 👌
